<?
$PERM["buyers"]["6"]="R";
$PERM["buyers"]["*"]="D";
$PERM["sellers"]["7"]="R";
$PERM["sellers"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>